services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  postgres_container:
    container_name: postgres_container
    image: postgres:13.3
    environment:
      - POSTGRES_DB=$POSTGRES_NAME_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGDATA=$POSTGRES_PGDATA
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - ./postgres/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pgdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.18
    environment:
      PGADMIN_DEFAULT_EMAIL: "habrpguser@habr.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4habr"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
  auth_server:
    build: ./auth_server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_AUTH_SERVER_LOCAL_PORT:$NODE_AUTH_SERVER_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    depends_on:
      - mongodb
    networks:
      default:
        aliases:
          - auth.dev
  server:
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_SERVER_LOCAL_PORT:$NODE_SERVER_DOCKER_PORT
    environment:
      - POSTGRES_DB_HOST=postgres_container
      - POSTGRES_DB_USER=$POSTGRES_USER
      - POSTGRES_DB_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB_NAME=$POSTGRES_NAME_DB
      - POSTGRES_DB_PORT=$POSTGRES_DOCKER_PORT
    stdin_open: true
    tty: true
    depends_on:
      postgres_container:
        condition: service_healthy
    networks:
      default:
        aliases:
          - my-api.dev
volumes:
  pgdata:
  db: